### ISSUE TITLE
Bad handling of Yaml in diff around string

### ISSUE THREAD

**Issue by LasneF** [pb33f/openapi-changes#135]
given the snippet 
```
  schemas:
    Pet:
      type: object
      properties:
        id:
          readOnly: true
          type: string
        name:
          type: string
          enum: 
            - Bob
```

and this snippet 
```
  schemas:
    Pet:
      type: object
      properties:
        id:
          readOnly: true
          type: string
        name:
          type: string
          enum: 
            - "Bob"

```

it is shown as differnt (add / remove) where this in yml stuff
